import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "../../loading";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <main className="mx-auto  bg-gradient-to-r from-teal-500 to-pink-500">
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </main>
      </body>
    </html>
  );
}
